# Project information
site_name: 'SDTDocs Online Documentation'
site_description: 'MkDocs Online Documentation'
site_author: 'Jim Pallister'

# Copyright
copyright: '&copy; 2019-2021 SDT Ultrasound Solutions'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/SDT-North-America-Inc/'

# Configuration
docs_dir: 'docs'
site_dir: 'site'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: 'blue'
    accent: 'blue'
  features:
    - tabs
  logo: 'https://sdt.media/md/uas4/SDT-Help-132x28.png'
  favicon: 'assets/images/favicon.ico'
  font:
    text: 'IBM Plex Serif'
    code: 'Source Code Pro'
  #icon:
    #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'
  extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
